### PR TITLE
QA Content Updates (MCPAR)

### PR DESCRIPTION
**Pull request by karla-vm**
### Description

Updating content based on comments from Kim and Nat after QA testing.

**Note:** A lot of the changes to this PR are related to an issue with `ESLint`, see this Slack thread for more info: https://coforma.slack.com/archives/C03GZ934P17/p1722461487969829 

### Related ticket(s)

N/A

---
### How to test

Create a report and verify the content is good against Figma.

### Notes

---
### Pre-review checklist

- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
- [ ] I have performed a self-review of my code
- [ ] I have manually tested this PR in the deployed cloud environment

---
#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

#### Security
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._

- [ ] These changes are significant enough to require an update to the SIA.
- [ ] These changes are significant enough to require a penetration test.
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Comment by britt-mo** [comment]
I don't see anything suspect in the PR but the `eslint` errors around `error`, `err`, and `e` are odd. Do you see them locally? Wonder if there was a recent update that we need to account for? the `eslintrc.yaml` has

```
 '@typescript-eslint/no-unused-vars': 
    - error
    - argsIgnorePattern: "^_" 
```

[I also saw there's a bug around this error](https://github.com/typescript-eslint/typescript-eslint/issues/5745)
`6:10  error  'maskMap' is defined but only used as a type  @typescript-eslint/no-unused-vars`

**Review by gmrabian — DISMISSED** [review]
what a ride

**Review by gmrabian — DISMISSED** [review]
🙌

**Review by gmrabian — APPROVED** [review]
this works too!

**Pull request merged**
