### PR TITLE
added gitleaks and pre-commit for secret scanning

### PR DESCRIPTION
**Pull request by KaushikSamtek**
### Related ticket(s)

MDCT-1459

---
### Important updates

---
### Author checklist

- [X] I have performed a self-review of my code
- [X] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [X] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Comment by KaushikSamtek** [comment]
Hey Brax, I added the secret scanning tools to this pipeline. It shows some checks as failed but they ran successfully. They found errors in the repo which is why they show as failed.

**Comment by KaushikSamtek** [comment]
Hey @oweingrod-coforma, I made the changes and created the allowlist config file to allow the .test.json files. Now gitleaks passes with no issues. Please check it out and let me know.

**Comment by KaushikSamtek** [comment]
I think you should look at it and let me know. I think one of the preconfigured tools is catching that secret.

**Comment by KaushikSamtek** [comment]
@oweingrod-coforma @braxex I fixed the issue. The secret was a dummy secret so I just removed it and ran it again. It seems to have worked now. Please check it out and confirm so I can apply this to the other 4 repos. Thank you

**Comment by oweingrod-coforma** [comment]
Looks good! Approved.

**Review by oweingrod-coforma — APPROVED** [review]

**Review by BearHanded — APPROVED** [review]

**Pull request merged**
