### PR TITLE
Cmdct 3802 - PDF banner button should not be displayed if the PDF has an error, a spinner if the PDF is not loaded

### PR DESCRIPTION
**Pull request by britt-mo**
### Description
The user always sees an active button to download the PDF version of the report, regardless of if the PDF has been generated. This PR addresses this issue by adding a spinner if the report has not generated, or does not display if there is an error message.

### Related ticket(s)

CMDCT-3802

---
### How to test
Create a program, go to the review and submit, go to pdf, see that the button is a spinner if the PDF isn't generated -- you can set the check on line 38 in `<ExportedReportBanner />` to `false` . To see the loader. Also, Garrett was able to see the spinner after  deleting the mcr-store in local storage.

In `<ExportedSectionHeading />`, remove lines 35 - 41, leaving only `{sectionInfo}` and see that the pdf banner does not display at all.

### Notes

---
### Pre-review checklist

- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
- [ ] I have performed a self-review of my code
- [ ] I have manually tested this PR in the deployed cloud environment

---
#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

#### Security
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._

- [ ] These changes are significant enough to require an update to the SIA.
- [ ] These changes are significant enough to require a penetration test.
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Review by gmrabian — COMMENTED** [review]
I think having a spinner when the page has an error might be confusing. To me it makes it seem like something might be happening, or it will change eventually to a non-error state.

Wasn't able to see the spinner for normal pdf load because it seems to render the header alongside the report

**Comment by britt-mo** [comment]
@gmrabian I can ask design how they feel about it

**Review by gmrabian — COMMENTED** [review]
I was able to get the spinner to show briefly by deleting the mcr-store in local storage

The error state looks good with not header.
Is the footer supposed to be floating in the middle there?
Screenshot 2024-07-22 at 9 13 04 AM

**Comment by karla-vm** [comment]
> I was able to get the spinner to show briefly by deleting the mcr-store in local storage
> 
> The error state looks good with not header. Is the footer supposed to be floating in the middle there? Screenshot 2024-07-22 at 9 13 04 AM

I don't think it's supposed to be floating up there, but I'm not really sure 🤔

**Review by karla-vm — COMMENTED** [review]
LGTM, although we may want to look at the footer display issue @gmrabian pointed out.

**Comment by britt-mo** [comment]
@gmrabian undid the changes in <App /> that had messed up the container styling. New logic in <ExportedReportBanner /> to determine displaying or not.

**Review by karla-vm — APPROVED** [review]

**Review by gmrabian — APPROVED** [review]

**Pull request merged**
