### PR TITLE
[MCR] Extend NumberField masking to allow per-field rounding

### PR DESCRIPTION
**Pull request by ajaitasaini**
### Description

Currently, we round every number field to 2 decimal places. Changing this so the default now becomes no rounding, and we can instead pass in specific rounding based on the field.

### Related ticket(s)

MDCT-2645

---
### How to test

- Login to MCR 
- Open MCPAR and open/add a submission
- Fill out number fields that both autosave and save on submit, confirm that the float value is being saved to the db and the comma-separated string is being displayed to the user
- Confirm that currency fields are rounded to 2 decimal places and other numeric fields are not rounding 
- Confirm that masking is working as expected
- Confirm that when reviewing PDF, values are comma-separated as needed
- Currency field experience:
    - https://github.com/Enterprise-CMCS/macpro-mdct-mcr/assets/6752256/65bece0b-ea42-46c9-9f3b-f020fe54e7e1
- Default numeric field experience:
    - https://github.com/Enterprise-CMCS/macpro-mdct-mcr/assets/6752256/d4999f05-79e4-4686-9151-43c266cea1b7

### Important updates

---
### Author checklist

- [x] I have performed a self-review of my code
- [x] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Review by karla-vm — DISMISSED** [review]
Looks good!

**Comment by ntsummers1** [comment]
Screenshot 2023-07-19 at 11 30 34 AM

Do we consider this correct in that the mask is showing a value different then whats sent?

**Review by keeysnc — DISMISSED** [review]
Looks good!

**Review by benmartin-coforma — DISMISSED** [review]
Haven't tested, but the code looks clean 👍

**Review by BearHanded — CHANGES_REQUESTED** [review]
One of the unit tests are failing, is this related?

**Comment by ajaitasaini** [comment]
@BearHanded unrelated to the other test failures! (chatted about this offline, commenting for documentation purposes) just put up a fix for the failing unit test

**Review by BearHanded — DISMISSED** [review]

**Review by britt-mo — DISMISSED** [review]

**Comment by braxex** [comment]
> Screenshot 2023-07-19 at 11 30 34 AM
> 
> Commas aside, do we consider this correct in that the mask is showing a value different then whats sent?

@ntsummers1 @ajaitasaini We should talk to product about this one.

**Comment by braxex** [comment]
Closing for now. Can revisit in the future.

**Review by benmartin-coforma — DISMISSED** [review]

**Review by braxex — CHANGES_REQUESTED** [review]
We need to address this one:
https://github.com/Enterprise-CMCS/macpro-mdct-mcr/pull/11380#issuecomment-1663861793

**Comment by ntsummers1** [comment]
> We need to address this one: [#11380 (comment)](https://github.com/Enterprise-CMCS/macpro-mdct-mcr/pull/11380#issuecomment-1663861793)

Based on my test this morning it looks like this is fixed on the standard report page. However, in the drawer i'm seeing commas in the data sent:

Screenshot 2023-08-07 at 12 21 52 PM

**Review by ntsummers1 — CHANGES_REQUESTED** [review]
See above comment I should have made through this review: https://github.com/Enterprise-CMCS/macpro-mdct-mcr/pull/11380#issuecomment-1668195117

**Comment by ajaitasaini** [comment]
@braxex we are sending the rounded value to the database!

**Comment by ajaitasaini** [comment]
@ntsummers1 thanks for the catch! I believe the reason why the database was receiving the comma-separated string is because we were originally sending the cleaned value *only* for autosaved fields. I changed it so that fields that are saved on submit (like number fields in a drawer) also send the cleaned value to the database.

**Comment by ajaitasaini** [comment]
update: changes to how we send values to the database began to affect values being retrieved from the database -> PDF. Pulled out comma-separating functionality into its own function and applied that on number fields for PDF.

**Review by braxex — APPROVED** [review]
Looks reasonable. Haven't pulled down to run.

**Review by braxex — CHANGES_REQUESTED** [review]
Realized we still need to extend functionality for specifying per-field rounding in form.json and then update both mcpar.json and mlr.json with that. We'll do these as a fast-follow. 

Placed a blocker here until we get the `regex` stuff figured out.

**Review by braxex — APPROVED** [review]

**Review by ntsummers1 — APPROVED** [review]
Excellent work!

**Pull request merged**
